### ISSUE TITLE
tab.favIconUrl is undefined

### ISSUE THREAD

**Issue by tomasko126** [tomasko126/notemark#12]
Repro steps:
1. Go to http://dsl.sk
2. Try to bookmark that site

Expected behavior:
Site is successfully bookmarked

Actual behavior :
Stack trace:
Error in response to tabs.query: TypeError: Cannot read property 'indexOf' of undefined
    at chrome-extension://pdiocncailfnckmlnkldobknjkfenipm/button/popup.js:62:35
    at Object.callback (chrome-extension://pdiocncailfnckmlnkldobknjkfenipm/button/popup.js:133:13)
    at Object.Sites.getCurrentTabInfo (chrome-extension://pdiocncailfnckmlnkldobknjkfenipm/button/popup.js:132:21)
    at HTMLDivElement.<anonymous> (chrome-extension://pdiocncailfnckmlnkldobknjkfenipm/button/popup.js:57:18)

**Comment by tomasko126** [comment]
Fixed in https://github.com/tomasko126/notemark/pull/13

**Comment by studiotbt** [comment]
works like a charm!
